### ISSUE TITLE
recent upgrade to boost 1.67.0 breaks ROS libraries

### ISSUE THREAD

**Issue by dominiquehunziker** [ros/meta-ros#592] opened 2018-05-05 23:03 UTC
The recent upgrade to boost 1.67.0 in openembedded-core breaks the build due to a change in boost's date_time module. Namely, the constructor for sub-second durations now has a [check in place that the argument is of integral type](https://github.com/boostorg/date_time/blob/boost-1.67.0/include/boost/date_time/time_duration.hpp#L285-L286).
Before, the ROS code relied on an implicit conversion of floating point to integral type.

**Comment by bulwahn** [comment] 2018-05-14 19:31
After the first two preliminary patches were applied with #590, these four further packages need to be addressed:
```
Summary: 4 tasks failed:
  /home/lukas/repositories/github.com/bmwcarit/meta-ros/recipes-ros/actionlib/actionlib_1.11.13.bb:do_compile
  /home/lukas/repositories/github.com/bmwcarit/meta-ros/recipes-ros/bond-core/bondcpp_1.7.20.bb:do_compile
  /home/lukas/repositories/github.com/bmwcarit/meta-ros/recipes-ros/vision-opencv/cv-bridge_1.11.16.bb:do_configure
  /home/lukas/repositories/github.com/bmwcarit/meta-ros/recipes-devtools/yaml-cpp/yaml-cpp_0.5.3.bb:do_compile
```
(This is mainly for me to remember the current state or someone to check if we are aware of the problems users might encounter.)


Packages that fail and need to be addressed:

- [x] actionlib: do_compile error is resolved with the commit ros/actionlib@677e952.
- [x] bondcpp: do_compile error in bondcpp/src/bond.cpp:221:94 is resolved with commit https://github.com/ros/bond_core/commit/1240bce50ca1538cdad07dc472d31797257e0851.
- [ ] camera-calibration-parsers: `boost_python3 is not found` during do_configure.
- [ ] cv-bridge: `boost_python3 is not found` during do_configure.
- [x] yaml-cpp: Issue can be resolved by updating to 0.6.2.

Note:
To fix `boost_python3 is not found` during do_configure, we must probably touch the boost recipe.

With the yaml-cpp update, the actionlib and bondcpp patch, `bitbake core-image-ros-world` compiles successfully with `ROS_USE_PYTHON3 = "no"`, and currently fails for camera-calibration-parsers and cv-bridge when `ROS_USE_PYTHON3 = "yes"`.

**Comment by bulwahn** [comment] 2018-05-14 19:58
For the actionlib issue, this patch is already available upstream, which might solve the issue:
https://github.com/ros/actionlib/commit/677e952fcbfe49e6e4c5b835357f88740f49c6ff

**Comment by shr-project** [comment] 2018-05-15 16:13
See the fixes in:
https://github.com/shr-project/meta-ros/commits/jansa/master

I've few more changes in that branch to fix the build with gcc8 (from http://lists.openembedded.org/pipermail/openembedded-core/2018-May/150461.html).

I haven't sent them in PR, because I cannot properly test them in runtime, but feel free to test the changes from there and apply them as you wish.

**Comment by bulwahn** [comment] 2018-05-17 07:18
@shr-project I had a look at your patches, and now provided a pull request for boost-1.67 update issues. Could you possibly report back the `boost_python3 is not found` issue? To reproduce it, just switch on `ROS_USE_PYTHON3 = "yes"` and `bitbake cv-bridge`. I believe that is a general issue with the boost recipe.

**Comment by bulwahn** [comment] 2018-05-17 10:25
You need to include `ROS_USE_PYTHON3 = "yes"` in your local.conf, and then you should be able to see camera-calibration-parsers and cv-bridge failing in do_configure.

**Comment by bulwahn** [comment] 2018-06-30 10:28
The boost_python3 issue was reported in the yocto project bugzilla: https://bugzilla.yoctoproject.org/show_bug.cgi?id=12833

**Comment by herb-kuta-lge** [comment] 2019-07-02 23:39
No longer occurs in the [thud-draft] branch. @dominiquehunziker < Can this issue be closed?

**Comment by herb-kuta-lge** [comment] 2019-08-13 22:37
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).

**Closed as completed** 2019-11-04 07:53 UTC
